[package]
name = "puzzle"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
egui_extras = { version = "0.23.0", features = ["all_loaders"] }
eframe = "0.23.0"
image = "0.24.7"
lazy_static = "1.4.0"
rand = "0.8.5"




[features]
debug = []