[package]
name = "puzzle"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
egui_extras = { version = "0.23.0", features = ["all_loaders"] }
eframe = "0.23.0"
image = "0.25.6"
lazy_static = "1.5.0"
rand = "0.9.0"

[features]
debug = []